/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author asus
 */
public class FormData extends javax.swing.JInternalFrame {
    
    DefaultTableModel model;
    koneksi konek = new koneksi();
    /**
     * Creates new form FormData
     */
    //consturctor
    public FormData() {
        initComponents();
        loadData("");
    }
    
    private void loadData(String Key){
        model = new DefaultTableModel();
        
        tableDataPasien.setModel(model);
        
        model.addColumn("Nama");
        model.addColumn("Kartu Identitas");
        model.addColumn("No. kartu identitas");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Tempat tanggal lahir");
        model.addColumn("Status");
        model.addColumn("Nama Wali");
        model.addColumn("No.telp");
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            Connection c = konek.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "";
            
            if (Key.isEmpty()) {
                sql = "SELECT * FROM dbDataPasien";
            } else {
                sql = "SELECT * FROM dbDataPasien WHERE namaPasien "
                        + "LIKE '%"+ Key + "%'";
            }
                    
            ResultSet rs = s.executeQuery(sql);
            
            while (rs.next()) {                
                Object[] obj = new Object[8];
                
                obj[0] = rs.getString("namaPasien");
                obj[1] = rs.getString("kartuIdentitasPasien");
                obj[2] = rs.getString("noKartuIdentitasPasien");
                obj[3] = rs.getString("jenisKelaminPasien");
                obj[4] = rs.getString("tempatTanggalLahirPasien");
                obj[5] = rs.getString("statusPasien");
                obj[6] = rs.getString("namaWaliPasien");
                obj[7] = rs.getString("noTelpPasien");
                
                model.addRow(obj);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNamaPasien = new javax.swing.JTextField();
        txtKartuIdentitasPasien = new javax.swing.JTextField();
        txtNoKartuIdentitasPasien = new javax.swing.JTextField();
        jComboJenisKelaminPasien = new javax.swing.JComboBox<>();
        txtTempatTanggalLahirPasien = new javax.swing.JTextField();
        jComboStatusPasien = new javax.swing.JComboBox<>();
        txtNamaWaliPasien = new javax.swing.JTextField();
        txtNoTelpPasien = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNamaPenjaminPasien = new javax.swing.JTextField();
        txtNoTelpPenjaminPasien = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNamaPetugasPasien = new javax.swing.JTextField();
        txtShiftPetugasPasien = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtDokterPasien = new javax.swing.JTextField();
        jComboJenisRawatPasien = new javax.swing.JComboBox<>();
        rButtonUmum = new javax.swing.JRadioButton();
        rButtonLab = new javax.swing.JRadioButton();
        rButtonUGD = new javax.swing.JRadioButton();
        btnSubmit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDataPasien = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jCheckBox1.setText("jCheckBox1");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("DATA PASIEN");

        jPanel1.setBackground(new java.awt.Color(230, 223, 223));

        jLabel2.setText("Nama");

        jLabel3.setText("Kartu Identitas");

        jLabel4.setText("No. kartu identitas");

        jLabel5.setText("Jenis kelamin");

        jLabel6.setText("Tempat tanggal lahir");

        jLabel7.setText("Status");

        jLabel8.setText("Nama wali");

        jLabel9.setText("No. Telp");

        jComboJenisKelaminPasien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita", " " }));

        txtTempatTanggalLahirPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempatTanggalLahirPasienActionPerformed(evt);
            }
        });

        jComboStatusPasien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum menikah", "Menikah" }));

        txtNamaWaliPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaWaliPasienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamaWaliPasien, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboJenisKelaminPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtKartuIdentitasPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNoKartuIdentitasPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTempatTanggalLahirPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboStatusPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNoTelpPasien))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKartuIdentitasPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNoKartuIdentitasPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboJenisKelaminPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTempatTanggalLahirPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboStatusPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNamaWaliPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoTelpPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(230, 223, 223));

        jLabel12.setText("Nama Penjamin");

        jLabel13.setText("No.telp penjamin");

        txtNamaPenjaminPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPenjaminPasienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNoTelpPenjaminPasien)
                    .addComponent(txtNamaPenjaminPasien))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNamaPenjaminPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNoTelpPenjaminPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(230, 223, 223));

        jLabel14.setText("Nama Petugas");

        jLabel15.setText("Shift");

        txtNamaPetugasPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPetugasPasienActionPerformed(evt);
            }
        });

        txtShiftPetugasPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShiftPetugasPasienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNamaPetugasPasien, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(txtShiftPetugasPasien))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNamaPetugasPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtShiftPetugasPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(230, 223, 223));

        jLabel16.setText("Check up");

        jLabel17.setText("Dokter");

        jLabel18.setText("Jenis Rawat");

        jLabel19.setText("Check");

        txtDokterPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDokterPasienActionPerformed(evt);
            }
        });

        jComboJenisRawatPasien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        rButtonUmum.setText("Umum");

        rButtonLab.setText("Lab");

        rButtonUGD.setText("UGD");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(rButtonUmum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rButtonLab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rButtonUGD)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboJenisRawatPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDokterPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(rButtonUmum)
                    .addComponent(rButtonLab)
                    .addComponent(rButtonUGD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDokterPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jComboJenisRawatPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jButton2.setText("Menu");

        jButton3.setText("Batal");

        tableDataPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tableDataPasien.setEditingColumn(6);
        tableDataPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataPasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDataPasien);

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(74, 74, 74)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(btnSubmit)
                            .addComponent(jButton2))
                        .addContainerGap(174, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDokterPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDokterPasienActionPerformed
   // TODO add your handling code here:
    }//GEN-LAST:event_txtDokterPasienActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        String nama_pasien = txtNamaPasien.getText();
        String kartu_identitas_pasien = txtKartuIdentitasPasien.getText();
        String no_kartu_identitas_pasien = txtNoKartuIdentitasPasien.getText();
        String jenis_kelamin_pasien = String.valueOf(jComboJenisKelaminPasien.getSelectedItem());
        String tempat_tanggal_lahir_pasien = txtTempatTanggalLahirPasien.getText();
        String status_pasien =  String.valueOf(jComboStatusPasien.getSelectedItem());
        String nama_wali_pasien = txtNamaWaliPasien.getText();
        String no_telp_pasien = txtNoTelpPasien.getText();
        String nama_penjamin_pasien = txtNamaPenjaminPasien.getText();
        String no_telp_penjamin_pasien = txtNoTelpPenjaminPasien.getText();
        String nama_petugas_pasien = txtNamaPetugasPasien.getText();
        String shift_petugas_pasien = txtShiftPetugasPasien.getText();
        //Radio Button below
        String  check_up_pasien = "";
            if(rButtonUmum.isSelected()){
                check_up_pasien = "Umum";
            } else if(rButtonLab.isSelected()){
                check_up_pasien = "Lab";
            } else if(rButtonUGD.isSelected()){
                check_up_pasien = "UGD";
            }
        //end of radio button
        String dokter_pasien = txtDokterPasien.getText();
        String jenis_rawat_pasien = String.valueOf(jComboJenisRawatPasien.getSelectedItem());      
        
        
        
        try {
            Connection c = konek.getKoneksi();
            String sql = "INSERT INTO dbDataPasien(`namaPasien`, `kartuIdentitasPasien`, `noKartuIdentitasPasien`, `jenisKelaminPasien`, `tempatTanggalLahirPasien`, `statusPasien`, `namaWaliPasien`, `noTelpPasien`, `namaPenjaminPasien`, `noTelpPenjaminPasien`, `namaPetugasPasien`, `shiftPetugasPasien`, `checkUpPasien`, `dokterPasien`, `jenisRawatPasien`) "
                    + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1,nama_pasien);
            p.setString(2,kartu_identitas_pasien);
            p.setString(3,no_kartu_identitas_pasien);
            p.setString(4,jenis_kelamin_pasien);
            p.setString(5,tempat_tanggal_lahir_pasien);
            p.setString(6,status_pasien);
            p.setString(7,nama_wali_pasien);
            p.setString(8,no_telp_pasien);
            p.setString(9,nama_penjamin_pasien);
            p.setString(10,no_telp_penjamin_pasien);
            p.setString(11,nama_petugas_pasien);
            p.setString(12,shift_petugas_pasien);
            p.setString(13,check_up_pasien);
            p.setString(14,dokter_pasien);
            p.setString(15,jenis_rawat_pasien);
            
            p.executeUpdate();
            
        } catch (SQLException e) {
            System.out.println("Gagal Input data");
        }finally{
            JOptionPane.showMessageDialog(rootPane,
                    "Berhasil menyimpan data","berhasil",
                    JOptionPane.INFORMATION_MESSAGE);
            
                    loadData("");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtTempatTanggalLahirPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempatTanggalLahirPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempatTanggalLahirPasienActionPerformed

    private void txtNamaWaliPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaWaliPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaWaliPasienActionPerformed

    private void txtNamaPenjaminPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPenjaminPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPenjaminPasienActionPerformed

    private void txtShiftPetugasPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShiftPetugasPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtShiftPetugasPasienActionPerformed

    private void tableDataPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataPasienMouseClicked
        // TODO add your handling code here:
        int i = tableDataPasien.getSelectedRow();
        if (i == -1) {
            return;
        }
        String nama_pasien = (String) model.getValueAt(i, 0);
        String kartu_identitas_pasien = (String) model.getValueAt(i, 1);
        String no_kartu_identitas_pasien = (String) model.getValueAt(i, 2);
        String jenis_kelamin_pasien = (String) model.getValueAt(i, 3);
        String tempat_tanggal_lahir_pasien = (String) model.getValueAt(i, 4);
        String status_pasien = (String) model.getValueAt(i, 5);
        String nama_wali_pasien = (String) model.getValueAt(i, 6);
        String no_telp_pasien = (String) model.getValueAt(i, 7);
        String nama_penjamin_pasien, no_telp_penjamin_pasien, nama_petugas_pasien, shift_petugas_pasien, check_up_pasien, dokter_pasien, jenis_rawat_pasien;
        
        
        
        try {
            Connection c = konek.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT namaPenjaminPasien,noTelpPenjaminPasien,namaPetugasPasien,shiftPetugasPasien,checkUpPasien,dokterPasien,jenisKelaminPasien FROM "
                        + "dbDataPasien WHERE kartuIdentitasPasien = '" + kartu_identitas_pasien +"'";
            
            ResultSet rs = s.executeQuery(sql);
            
            while (rs.next()) {
                Object[] obj = new Object[7];
                
                
            }
            
         
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tableDataPasienMouseClicked

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String cariData = txtSearch.getText();
        loadData(cariData);
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String cariData = txtSearch.getText();
        loadData(cariData);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtNamaPetugasPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPetugasPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPetugasPasienActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboJenisKelaminPasien;
    private javax.swing.JComboBox<String> jComboJenisRawatPasien;
    private javax.swing.JComboBox<String> jComboStatusPasien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rButtonLab;
    private javax.swing.JRadioButton rButtonUGD;
    private javax.swing.JRadioButton rButtonUmum;
    private javax.swing.JTable tableDataPasien;
    private javax.swing.JTextField txtDokterPasien;
    private javax.swing.JTextField txtKartuIdentitasPasien;
    private javax.swing.JTextField txtNamaPasien;
    private javax.swing.JTextField txtNamaPenjaminPasien;
    private javax.swing.JTextField txtNamaPetugasPasien;
    private javax.swing.JTextField txtNamaWaliPasien;
    private javax.swing.JTextField txtNoKartuIdentitasPasien;
    private javax.swing.JTextField txtNoTelpPasien;
    private javax.swing.JTextField txtNoTelpPenjaminPasien;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtShiftPetugasPasien;
    private javax.swing.JTextField txtTempatTanggalLahirPasien;
    // End of variables declaration//GEN-END:variables
}
